Updates to latest Zipkin and skips Cassandra row on parse error
This makes it possible to troubleshoot bad data in cassandra by logging
the lookup keys on the row that failed to parse.

Currently, there's no way to unit test this, so I created a malformed
span and tested manually.

```
17:08:25.628 [Executor task launch worker-0] WARN  z.d.c.CassandraDependenciesJob - Unable to decode span from traces where trace_id=-3823313327434446729 and ts=1475542133045 and span_name='-2048755551635407690_1508523804_-73907135'
java.lang.IllegalArgumentException: Malformed reading Span from TBinary:
	at zipkin.internal.ThriftCodec.exceptionReading(ThriftCodec.java:567)
--snip--
```